language: node_js
node_js:
  - 16.13.1
addons:
  apt:
    packages:
      - xvfb
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
cache:
  npm: false
env:
  global:
    - secure: fI10dGRbWPDSZB7CLFbzUqAz6YxYGgXeL2Vls9oESfu6TXtPJ+VQgBnmFqBS5JMeDGaZ1ua4Sx3YqjN3c3mnnA8160plSZ/ULEj7tK09MtW/NPHPzDcIk0wmNPbI2pcc031lcwQLfHhTsjgC1JJII3hZpYYSI0Gf5CbgDQwzRgS2qEAl9LqlQDxfZJUI9hW8GzLhWwDBC+fX5GiSDtu7cK49G0lqGcb78LqVzALsXeC11UuFIDP2neum1gSaYZgnE+83whb5Cf1agsgdeqLxholt0VbxtQS4lt4yyNB3DcM5amktK3vrV7wOAeOfUQ1vQ6vpOsbbbc9uJHLpDV667Pj+gw+N2Em1An5XvLggtGB76W2aXJaerdE42TkrN4JwolHdFPaMC5wuFd1juSfYIV9jlgkleY7kSR6jlBNamfP6VwKtMYjuJHE5FunNKFeGLt/3ygvJlRWCVc89TrFTS4vQL2157ZtOAOPlzvI+4vBAZzGtJkzIml/5/UTouZCbHh+ebEl/EPiqHDWQMNOWo//MMADBd/gQpbNbkdBPB8Z6wl03qmW1VYFROSGG5AkZC+o86aLCgaBFTD2a3ndLlOzzpUiLHtS92JnIu3iGzRZcz/sQkjBPY99C/OZoDaUmYOfmhFlL8VRF5AJ77PAaLDRRguLeZXtU/H1XPQ5Nmyo=
